harder better faster stronger

diff --git a/bins/alien b/bins/alien
--- a/bins/alien
+++ b/bins/alien
@@ -1,56 +1,39 @@
 #!/bin/bash
-VIRO_HOME="${VIRO_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"
+source "$VIRO_HOME/src/utils.sh"
 
-source "$VIRO_HOME/src/log.sh"
+ALIEN="$VIRO_HOME/user/aliases"
 
 # Flags
 # NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
 # =====================================================================================================================
-
-ALIEN="$VIRO_HOME/user/aliases"
-
 PARAMS=""
 while (( "$#" )); do case "$1" in
+  -h|--help) man "${BASH_SOURCE[0]}" && exit 0;;
   --secret) ALIEN="$VIRO_HOME/user/secret_aliases" && shift;;
-  --)
-    shift
-    break
-    ;;
-  -*|--*)
-    log "Error: Unsupported flag $1" >&2
-    exit 1
-    ;;
-  *)
-    PARAMS="$PARAMS $1"
-    shift
-    ;;
+
+  --) shift && break;;
+  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
+  *) PARAMS="$PARAMS $1" && shift;;
 esac; done
 eval set -- "$PARAMS"
 
 mkdir -p "$(dirname "$ALIEN")" && touch "$ALIEN"
 case "$1" in
-  ls|show|view) sed -e "s/=/~/" -e "s/alias/[alien]/" -e "s/'//g" < "$ALIEN" | column -t -s~;;
-  edit) "$VISUAL" "$ALIEN" && exec bash;;
-  a|add|create|new)
-    [[ -z "$2" ]] && read -rp "name: " name
-    name="${name:-"$2"}"
-    [[ -z "$3" ]] && read -rp "command: " cmd
+  ls) sed -e "s/=/~/" -e "s/alias //" -e "s/'//g" < "$ALIEN" | column -t -s~;;
+  create)
+    name="${2:-"$(prompt "name:")"}"
+    cmd="${3:-"$(prompt "command:")"}"
     cmd="${cmd:-"${@:3}"}"
-
     sed -i "/$name=/d" "$ALIEN"
-    echo "alias $name='$cmd'" >> "$ALIEN"
+    echo "alias $name=\"$cmd\"" >> "$ALIEN"
     log "added: $(grep "alias $name" "$ALIEN")"
-    exec bash
+    viro refresh
     ;;
-  r|rm|remove)
-    [[ -z "$2" ]] && name="$(sed -e 's/=./ /' < "$ALIEN" | awk '{print $2}' | fzf)"
-    name="${name:-"$2"}"
+  edit) "$VISUAL" "$ALIEN" && viro refresh;;
+  rm)
+    name="${2:-"$(sed -e 's/=./ /' < "$ALIEN" | awk '{print $2}' | choose)"}"
     [[ -z "$name" ]] && log "No aliases have been removed" && exit 1
-    name="${name:-"$2"}"
-
     log "removed: $(grep "alias $name" "$ALIEN")"
     sed -i "/$name=/d" "$ALIEN"
-    exec bash
-    ;;
-  *) man -l "$VIRO_HOME/.manpages/alien.1"
+    viro refresh
 esac
diff --git a/bins/bin b/bins/bin
--- a/bins/bin
+++ b/bins/bin
@@ -1,43 +1,60 @@
 #!/bin/bash
-VIRO_HOME="${VIRO_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"
+source "$VIRO_HOME/src/utils.sh"
 
-source "$VIRO_HOME/src/log.sh"
+BINS="$VIRO_HOME/user/bins"
 
 # Flags
 # NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
 # =====================================================================================================================
-
 PARAMS=""
 while (( "$#" )); do case "$1" in
-  --)
-    shift
-    break
-    ;;
-  -*|--*)
-    log "Error: Unsupported flag $1" >&2
-    exit 1
-    ;;
-  *)
-    PARAMS="$PARAMS $1"
-    shift
-    ;;
+  -h|--help) man "${BASH_SOURCE[0]}" && exit 0;;
+  --viro) BINS="$VIRO_HOME/bins" && shift;;
+
+  --) shift && break;;
+  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
+  *) PARAMS="$PARAMS $1" && shift;;
 esac; done
 eval set -- "$PARAMS"
 
+[[ -e "$BINS" ]] || mkdir -p "$BINS"
 case "$1" in
-  r|rm|remove) rm -rf "$VIRO_HOME/bins/$2";;
-  ls|show|view) ls "$VIRO_HOME/bins";;
-  rename) mv "$VIRO_HOME/bins/$2" "$VIRO_HOME/bins/$3";;
-  a|add|edit|create)
-    if [ -z "$1" ]; then
-      "$VISUAL" "$VIRO_HOME/bins/"
-    else
-      [ -x "$VIRO_HOME/bins/$2" ] || {
-        cp "$VIRO_HOME/templates/bin" "$VIRO_HOME/bins/$2"
-        chmod +x "$VIRO_HOME/bins/$2"
-      }
-      "$VISUAL" "$VIRO_HOME/bins/$2"
-    fi
+  ls) ls "$BINS";;
+  create)
+    name="${2:-"$(prompt "name:")"}"
+    [[ -z "$name" ]] && log "No bins were added" && exit 1
+    [[ -f "$BINS/$name" ]] && {
+      log "$name already exists"
+      log "try: bin edit $name"
+      exit 1
+    }
+    cp "$VIRO_HOME/templates/bin" "$BINS/$name"
+    [[ -x "$BINS/$name" ]] || chmod +x "$BINS/$name"
+    "$VISUAL" "$BINS/$name"
+    log "$name was created"
     ;;
-  *) man -l "$VIRO_HOME/.manpages/bin.1"
+  edit)
+    name=${2:-"$(ls "$BINS" | choose)"}
+    [[ -z "$name" ]] && log "Nothing to edit" && exit 1
+    [[ -f "$BINS/$name" ]] || {
+      log "$name doesn't exist"
+      log "try: bin create $name"
+      exit 1
+    }
+    [[ -x "$BINS/$name" ]] || chmod +x "$BINS/$name"
+    "$VISUAL" "$BINS/$name"
+    log "$name has been updated"
+    ;;
+  rm)
+    name=${2:-"$(ls "$BINS" | choose)"}
+    [[ -z "$name" ]] && log "No bins were removed" && exit 1
+    rm -rf "${BINS:?}/$name"
+    log "$name was removed"
+    ;;
+  rename)
+    old=${2:-"$(ls "$BINS" | choose)"}
+    new="${3:-"$(prompt "new name:")"}"
+    mv "$BINS/$old" "$BINS/$new"
+    log "renamed $old to $new"
+    ;;
 esac
diff --git a/bins/viro b/bins/viro
--- a/bins/viro
+++ b/bins/viro
@@ -1,71 +1,59 @@
 #!/bin/bash
-VIRO_HOME="${VIRO_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"
-
-source "$VIRO_HOME/src/log.sh"
+source "$VIRO_HOME/src/utils.sh"
 
 VIRO="$VIRO_HOME/user/ENV"
 
 # Flags
 # NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
 # =====================================================================================================================
-
 PARAMS=""
 while (( "$#" )); do case "$1" in
-  --secret)
-    VIRO="$VIRO_HOME/user/secret_ENV"
-    shift;;
-  --)
-    shift
-    break
-    ;;
-  -*|--*)
-    log "Error: Unsupported flag $1" >&2
-    exit 1
-    ;;
-  *)
-    PARAMS="$PARAMS $1"
-    shift
-    ;;
+  -h|--help) man "${BASH_SOURCE[0]}" && exit 0;;
+  --secret) VIRO="$VIRO_HOME/user/secret_ENV" && shift;;
+
+  --) shift && break;;
+  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
+  *) PARAMS="$PARAMS $1" && shift;;
 esac; done
 eval set -- "$PARAMS"
+
+refresh() {
+  log "applying..."
+  RELOAD="yes" exec bash;
+}
 
 apply() {
   rm  "$HOME/.bashrc"
   cp "$VIRO_HOME/templates/bashrc" "$HOME/.bashrc"
-  sed -i '/VIRO_HOME=/d' "$HOME/.bashrc"
-  sed -i "1i VIRO_HOME=\"$VIRO_HOME\"" "$HOME/.bashrc"
-  log "applied"
-  exec bash
+  sed -i -e '/VIRO_HOME=/d' "$HOME/.bashrc" -e "1i export VIRO_HOME=\"$VIRO_HOME\"" "$HOME/.bashrc"
+  refresh
 }
 
-mkdir -p "$(dirname "$VIRO")" && touch "$VIRO"
+[[ -e "$VIRO" ]] || mkdir -p "$(dirname "$VIRO")" && touch "$VIRO"
 case "$1" in
-  bashrc) "$VISUAL" "$VIRO_HOME/templates/bashrc" && apply;;
   apply) apply;;
-  ls|show|view) sed -e 's/export/[viro]/' -e 's/=/~/' -e "s/'//g" < "$VIRO" | column -t -s~;;
-  edit) "$VISUAL" "$VIRO" && exec bash;;
-  a|add|create|new)
-    [[ -z "$2" ]] && read -rp "name: " name
-    name="${name:-"$2"}"
+  ls) sed -e 's/export //' -e 's/=/~/' -e "s/'//g" < "$VIRO" | column -t -s~;;
+  edit) "$VISUAL" "$VIRO" && refresh;;
+  create)
+    name="${2:-"$(prompt "name:")"}"
     name="${name^^}" # ALL_CAPS
-    [[ -z "$3" ]] && read -rp "value: " value
+    value="${3:-"$(prompt "value:")"}"
     value="${value:-"${@:3}"}"
-
+    [[ -z "$name" ]]  && log "name empty. No ENV created." && exit 1
+    [[ -z "$value" ]] && log "value empty. No ENV created." && exit 1
     sed -i "/export $name=/d" "$VIRO"
-    echo "export $name='$value'" >> "$VIRO"
+    echo "export $name=\"$value\"" >> "$VIRO"
     log "added: $(grep "export $name" "$VIRO")"
-    exec bash
+    refresh
     ;;
-  r|rm|remove)
-    [[ -z "$2" ]] && name="$(sed -e 's/=./ /' < "$VIRO" | awk '{print $2}' | fzf)"
-    name="${name:-"$2"}"
+  rm)
+    name="${2:-"$(sed -e 's/=./ /' < "$VIRO" | awk '{print $2}' | choose)"}"
     [[ -z "$name" ]] && log "No ENV have been removed" && exit 1
-    name="${name:-"$2"}"
     name="${name^^}" # ALL_CAPS
-
-    log "removed: $( grep "export $name" "$VIRO" )"
+    log "removed: $(grep "export $name" "$VIRO")"
     sed -i "/export $name=/d" "$VIRO"
-    exec bash
+    refresh
     ;;
-  *) man -l "$VIRO_HOME/.manpages/viro.1"
+  bashrc) "$VISUAL" "$VIRO_HOME/templates/bashrc" && apply;;
+  refresh) refresh;;
 esac
diff --git a/templates/bashrc b/templates/bashrc
--- a/templates/bashrc
+++ b/templates/bashrc
@@ -1,10 +1,26 @@
-VIRO_HOME="/c/Users/tpoole/Documents/GitHub/bin"
+export VIRO_HOME="/c/Users/tpoole/Documents/GitHub/bin"
+export MANPATH="$VIRO_HOME/man"
+[[ -f "$VIRO_HOME/user/PATH" ]] && source "$VIRO_HOME/user/PATH";
 [[ -f "$VIRO_HOME/user/ENV" ]] && source "$VIRO_HOME/user/ENV";
 [[ -f "$VIRO_HOME/user/secret_ENV" ]] && source "$VIRO_HOME/user/secret_ENV";
 [[ -f "$VIRO_HOME/user/aliases" ]] && source "$VIRO_HOME/user/aliases";
+[[ -f "$VIRO_HOME/user/secret_aliases" ]] && source "$VIRO_HOME/user/secret_aliases";
 
 source "$VIRO_HOME/src/host/wsl-ubuntu.sh"
-source "$VIRO_HOME/src/log.sh"
+source "$VIRO_HOME/src/utils.sh"
+
+# Flags
+# NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
+# =====================================================================================================================
+PARAMS=""
+while (( "$#" )); do case "$1" in
+  --reload) RELOAD="yes" && shift;;
+
+  --) shift && break;;
+  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
+  *) PARAMS="$PARAMS $1" && shift;;
+esac; done
+eval set -- "$PARAMS"
 
 packages() {
   log "ensuring packages are available"
@@ -50,3 +66,4 @@ packages() {
   clone https://github.com/nvm-sh/nvm.git "$NVM_DIR"
   tmux attach || exec tmux new-session
 }
+[[ -n "$RELOAD" ]] && log "ready."
diff --git a/templates/bin b/templates/bin
--- a/templates/bin
+++ b/templates/bin
@@ -1,26 +1,16 @@
 #!/bin/bash
-VIRO_HOME="${VIRO_HOME:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" 2>&1 && cd ../ 2>&1 && pwd)"}"
-
-source "$VIRO_HOME/src/log.sh"
+source "$VIRO_HOME/src/utils.sh"
 
 # Flags
 # NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
 # =====================================================================================================================
-
 PARAMS=""
 while (( "$#" )); do case "$1" in
-  --)
-    shift
-    break
-    ;;
-  -*|--*)
-    log "Error: Unsupported flag $1" >&2
-    exit 1
-    ;;
-  *)
-    PARAMS="$PARAMS $1"
-    shift
-    ;;
+  -h|--help) man "${BASH_SOURCE[0]}" && exit 0;;
+
+  --) shift && break;;
+  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
+  *) PARAMS="$PARAMS $1" && shift;;
 esac; done
 eval set -- "$PARAMS"
 
