RC-1.0 (#3)

diff --git a/bins/bin b/bins/bin
--- a/bins/bin
+++ b/bins/bin
@@ -1,64 +1,58 @@
 #!/bin/bash
-# Bash Cheatsheet: https://devhints.io/bash
-BIN="$( ( cd ../ && dirname "${0%/*}" ) )";
-source "$BIN/src/core.sh"
+source "$VIRO_HOME/src/utils.sh"
+
+BINS="$VIRO_HOME/user/bins"
 
 # Flags
 # NOTE: if a flag takes an argument you need to `shift 2`, otherwise just `shift`
 # =====================================================================================================================
-
 PARAMS=""
 while (( "$#" )); do case "$1" in
-  --)
-    shift
-    break
-    ;;
-  -*|--*)
-    echo "Error: Unsupported flag $1" >&2
-    exit 1
-    ;;
-  *)
-    PARAMS="$PARAMS $1"
-    shift
-    ;;
+  -h|--help) man "${BASH_SOURCE[0]}" && exit 0;;
+  --core) BINS="$VIRO_HOME/bins" && shift;;
+
+  --) shift && break;;
+  -*|--*) log "Error: Unsupported flag $1" >&2 && exit 1;;
+  *) PARAMS="$PARAMS $1" && shift;;
 esac; done
 eval set -- "$PARAMS"
 
-# Logic
-# =====================================================================================================================
-
+[[ -e "$BINS" ]] || mkdir -p "$BINS"
 case "$1" in
-  meta)
-    echo "BIN=$BIN"
-    echo "OS=$OS"
-    echo "DISTRO=$DISTRO"
-    echo "BROWSER=$BROWSER"
-    echo "CLIPBOARD=$CLIPBOARD"
+  ls) ls "$BINS";;
+  create)
+    name="${2:-"$(prompt "name:")"}"
+    [[ -z "$name" ]] && log "No bins were added" && exit 1
+    [[ -f "$BINS/$name" ]] && {
+      log "$name already exists"
+      log "try: bin edit $name"
+      exit 1
+    }
+    cp "$VIRO_HOME/templates/bin" "$BINS/$name"
+    [[ -x "$BINS/$name" ]] || chmod +x "$BINS/$name"
+    "$VISUAL" "$BINS/$name"
     ;;
-  src)
-    if [ -z "$1" ]; then
-      "$VISUAL" "$BIN/src/"
-    else
-      "$VISUAL" "$BIN/src/$2.sh"
-    fi
+  edit)
+    name=${2:-"$(ls "$BINS" | choose)"}
+    [[ -z "$name" ]] && log "Nothing to edit" && exit 1
+    [[ -f "$BINS/$name" ]] || {
+      log "$name doesn't exist"
+      log "try: bin create $name"
+      exit 1
+    }
+    [[ -x "$BINS/$name" ]] || chmod +x "$BINS/$name"
+    "$VISUAL" "$BINS/$name"
     ;;
-  remove) rm -rf "$BIN/bins/$2";;
-  show|view) ls "$BIN/bins";;
-  rename) mv "$BIN/bins/$2" "$BIN/bins/$3";;
-  enter) cd "$BIN";;
-  edit|create)
-    if [ -z "$1" ]; then
-      "$VISUAL" "$BIN/bins/"
-    else
-      [ -x "$BIN/bins/$2" ] || {
-        cp "$BIN/bin.tmpl" "$BIN/bins/$2"
-        chmod +x "$BIN/bins/$2"
-      }
-      "$VISUAL" "$BIN/bins/$2"
-    fi
+  rm)
+    name=${2:-"$(ls "$BINS" | choose)"}
+    [[ -z "$name" ]] && log "No bins were removed" && exit 1
+    rm -rf "${BINS:?}/$name"
+    log "$name was removed"
     ;;
-  branch) (cd "$BIN" && git checkout "$2");;
-  commit) (cd "$BIN" && git add -A . && git commit -m "bin commit");;
-  push) (cd "$BIN" && git push);;
-  *) echo "that did nothing. nothing was done";;
+  rename)
+    old=${2:-"$(ls "$BINS" | choose)"}
+    new="${3:-"$(prompt "new name:")"}"
+    mv "$BINS/$old" "$BINS/$new"
+    log "renamed $old to $new"
+    ;;
 esac
